-- Migration: Populate reference tables for dietary preferences, allergies, and cuisines
-- Description: Adds the necessary data to support user registration preferences
-- Date: 2024-12-21

-- Populate dietary_preferences table
INSERT INTO dietary_preferences (id, name) VALUES
(1, 'Vegetarian'),
(2, 'Vegan'),
(3, 'Pescatarian'),
(4, 'Keto'),
(5, 'Paleo'),
(6, 'Mediterranean'),
(7, 'Low Carb'),
(8, 'Gluten-Free'),
(9, 'Dairy-Free'),
(10, 'Low Sodium'),
(11, 'High Protein'),
(12, 'Low Fat'),
(13, 'Whole30'),
(14, 'Intermittent Fasting'),
(15, 'Flexitarian'),
(16, 'Halal'),
(17, 'Kosher')
ON CONFLICT (id) DO NOTHING;

-- Populate allergies table
INSERT INTO allergies (id, name) VALUES
(1, 'Peanuts'),
(2, 'Tree Nuts'),
(3, 'Milk'),
(4, 'Eggs'),
(5, 'Wheat'),
(6, 'Soy'),
(7, 'Fish'),
(8, 'Shellfish'),
(9, 'Sesame'),
(10, 'Mustard'),
(11, 'Celery'),
(12, 'Lupin'),
(13, 'Sulfites'),
(14, 'Gluten'),
(15, 'Lactose')
ON CONFLICT (id) DO NOTHING;

-- Populate cuisines table
INSERT INTO cuisines (id, name) VALUES
(1, 'American'),
(2, 'Italian'),
(3, 'Mexican'),
(4, 'Chinese'),
(5, 'Japanese'),
(6, 'Thai'),
(7, 'Indian'),
(8, 'Mediterranean'),
(9, 'French'),
(10, 'Greek'),
(11, 'Spanish'),
(12, 'Korean'),
(13, 'Vietnamese'),
(14, 'Lebanese'),
(15, 'Turkish'),
(16, 'Brazilian'),
(17, 'Peruvian'),
(18, 'Ethiopian'),
(19, 'Moroccan'),
(20, 'German'),
(21, 'Nepalese'),
(22, 'Pakistani'),
(23, 'Bangladeshi'),
(24, 'Sri Lankan'),
(25, 'Afghan'),
(26, 'Iranian'),
(27, 'Iraqi'),
(28, 'Syrian'),
(29, 'Jordanian'),
(30, 'Israeli'),
(31, 'Armenian'),
(32, 'Georgian'),
(33, 'Russian'),
(34, 'Ukrainian'),
(35, 'Polish'),
(36, 'Hungarian'),
(37, 'Romanian'),
(38, 'Bulgarian'),
(39, 'Croatian'),
(40, 'Serbian'),
(41, 'Albanian'),
(42, 'Macedonian'),
(43, 'Bosnian'),
(44, 'Montenegrin'),
(45, 'Slovenian'),
(46, 'Slovak'),
(47, 'Czech'),
(48, 'Austrian'),
(49, 'Swiss'),
(50, 'Dutch'),
(51, 'Belgian'),
(52, 'Portuguese'),
(53, 'Swedish'),
(54, 'Norwegian'),
(55, 'Danish'),
(56, 'Finnish'),
(57, 'Icelandic'),
(58, 'Irish'),
(59, 'Scottish'),
(60, 'Welsh'),
(61, 'Canadian'),
(62, 'Australian'),
(63, 'New Zealand'),
(64, 'South African'),
(65, 'Nigerian'),
(66, 'Ghanaian'),
(67, 'Kenyan'),
(68, 'Egyptian'),
(69, 'Tunisian'),
(70, 'Algerian'),
(71, 'Libyan'),
(72, 'Sudanese'),
(73, 'Somali'),
(74, 'Ethiopian'),
(75, 'Eritrean'),
(76, 'Ugandan'),
(77, 'Tanzanian'),
(78, 'Zimbabwean'),
(79, 'Botswana'),
(80, 'Namibian')
ON CONFLICT (id) DO NOTHING;

-- Verify the data was inserted
SELECT 'dietary_preferences' as table_name, COUNT(*) as count FROM dietary_preferences
UNION ALL
SELECT 'allergies' as table_name, COUNT(*) as count FROM allergies
UNION ALL
SELECT 'cuisines' as table_name, COUNT(*) as count FROM cuisines;
